---
- hosts: all
  become: true
  remote_user: ubuntu

  vars:
    db_user: "database_user"
    db_password: "database_password"
    civicrm_db_name: "Civicrm_database_name"
    drupal_db_name: "Drupal_database_name"
    priv: "Drupal_database_name.*:ALL/Civicrm_database_name.*:ALL"
    root_db_password: "Your_root_password"
  
  roles:
    - setupMysql
    - secureMysql


