---
- name: Install AWSCLI
  command: pip install -U awscli
- name: ensure mysql is running
  service:
    name: mysql
    state: started
    enabled: true
- name: update mysql root password for all root account
  mysql_user:
    name: root
    login_host: localhost
    login_password: "{{ root_db_password }}"
- name: copy .my.cnf file with root password credentials
  template:
    src: .my.cnf
    dest: ~/.my.cnf
    owner: root
    mode: 0600
- name: remove all anonymous user account
  mysql_user:
    name: ''
    host_all: yes
    state: absent
- name: remove the test database
  mysql_db:
    name: test
    state: absent